config/routes.rb
SampleApp::Application.routes.draw do  

  resources :bartenders

  get '/pages/index' => redirect('/pages')
  
  resources :sessions, :only => [:new, :create, :destroy] do 
    collection do
      post :fb_signin
    end
  end
  
  resources :users do
  resources :bartenders, :only => [:create, :new]
    member do
      post :fb_unlink
      get :following, :followers       #makes users/1/following and following_user_path
    end
    collection do
      post :send_password_recovery
      get :password_recovery
      get :activate
      get :send_activation
      post :create_fb
      get :new_fb
    end
  end

  resources :base_objects
  resources :pages
  resources :relationships, :only => [:create, :destroy]

  root :to => "bartenders#index"
  get '/signup', :to => 'users#new'
  get '/contact', :to => 'pages#contact'
  get '/about', :to => 'pages#about'
  get '/signin', :to => 'sessions#new'
  get '/signout', :to => 'sessions#destroy'
  get '/admin', :to => 'pages#admin'
  get '/maintenance', :to => 'pages#maintenance'
  get '/error', :to => 'pages#error'
  get '/sitemap', :to => 'pages#site_map'
  get '/sitemap_xml', :to => 'pages#site_map_xml'

end

app/models/bartender.rb
class Bartender < ActiveRecord::Base

  attr_accessible :bar, :is_working, :user_id, :background
  belongs_to :user

  validates :user_id, :presence => true
  validates :bar, :length => { :within => 4..30 }

  mount_uploader :background, ImageUploader

  has_many :bartender_reverse_relationships, -> { where relationship_type: RELATIONSHIP_TYPE_BARTENDER }, :dependent => :destroy,
           :foreign_key => "followed_id",
           :class_name => "Relationship"
  has_many :followers, :through => :bartender_reverse_relationships, :source => :follower

  scope :top_bartenders, -> (limit) { select("count(relationships.id) as followers, bartenders.*")
  .joins("LEFT JOIN relationships ON relationships.followed_id = bartenders.id")
  .order("followers desc").group("relationships.id, bartenders.id")
  .limit(limit)}

  def follower_count
    followers.count
  end

end

app/controllers/bartenders_controller.rb
class BartendersController < ApplicationController

  before_action :set_bartender, only: [:show, :edit, :update, :destroy]
  before_filter :check_permissions, :only => [:edit, :update, :destroy]

  # GET /bartenders
  def index

    limit = 100
    if params[:limit]
      limit = params[:limit]
    end

    @bartenders = Bartender.top_bartenders(limit)

    if(params[:search])
      @bartenders = @bartenders.joins(:user).where("lower(bar) like lower('%#{params[:search]}%') or lower(users.name) like lower('%#{params[:search]}%')")
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bartenders }
    end

  end

  # GET /bartenders/1
  def show
  end

  # GET /bartenders/new
  def new
    @bartender = Bartender.new

    if params[:user_id]
      @bartender.user_id = params[:user_id]
    end

  end

  # GET /bartenders/1/edit
  def edit
  end

  # POST /bartenders
  def create
    @bartender = Bartender.new(bartender_params)

    if @bartender.save
      redirect_to @bartender, notice: 'Bartender was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /bartenders/1
  def update
    if @bartender.update(bartender_params)
      redirect_to @bartender, notice: 'Bartender was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /bartenders/1
  def destroy
    @bartender.destroy
    redirect_to bartenders_url, notice: 'Bartender was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bartender
      @bartender = Bartender.find(params[:id])
    end


  # Only allow a trusted parameter "white list" through.
  def bartender_params
    params.require(:bartender).permit(:bar, :user_id, :is_working, :background)
  end

  def check_permissions
    redirect_to(root_path, :flash => {:success =>"You Don't Have Access"}) unless  current_user and (current_user.admin or current_user.bartender == @bartender)
  end

end

app/helpers/bartenders_helper.rb
module BartendersHelper
end

app/views/bartenders/_bartender_thumb.html.erb
<div class="md-col-5 left padded block opaque">
  <%= link_to image_for(bartender.user, :size => 100), bartender %>
  <p><%= link_to bartender.user.name, bartender %> </p>
  <p>Works at: <%= bartender.bar %> </p>
  <p class="<%= bartender.is_working ? "green" : "red" %>">
    <%= bartender.is_working ? "Working" :"Not Working" %>
  </p>
</div>

app/views/bartenders/_form.html.erb
<%= form_for(@bartender) do |f| %>
  <% if @bartender.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bartender.errors.count, "error") %> prohibited this bartender from being saved:</h2>

      <ul>
      <% @bartender.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :bar %><br>
    <%= f.text_field :bar %>
  </div>
  <div class="field">
    <%= f.hidden_field :user_id, :value => @bartender.user_id %>
  </div>
  <div class="field">
    <%= f.label :is_working %><br>
    <%= f.check_box :is_working %>
  </div>

    <div class="field">
      <%= f.file_field :background %>
    </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bartenders/edit.html.erb
<h1>Editing bartender</h1>

<%= render 'form' %>

<%= link_to 'Show', @bartender %> |
<%= link_to 'Back', bartenders_path %>

app/views/bartenders/index.html.erb
<%= link_to 'New Bartender', new_bartender_path if current_user and current_user.admin? %>

<%= form_tag('/bartenders', :method => "GET") do %>
    <%= text_field_tag "search", nil, placeholder: "Search" %>
    <%= submit_tag "Go", :class => "search_button" %>
<% end %>

<h1>Top Bartenders</h1>

<div class="row">
<% @bartenders.each do |bartender| %>

    <%= render "bartender_thumb", :bartender => bartender %>

<% end %>
</div>

app/views/bartenders/new.html.erb
<h1>New bartender</h1>

<%= render 'form' %>

<%= link_to 'Back', bartenders_path %>

app/views/bartenders/show.html.erb
<p id="notice"><%= notice %></p>

<div>
<%= render "bartender_thumb", :bartender => @bartender %>
</div>

<div class="admin_actions block opaque left">
<% if current_user and ( current_user == @bartender.user or current_user.admin ) %>
    <%= link_to 'Edit', edit_bartender_path(@bartender), :class => "btn btn-primary" %>

    <%= link_to "delete", @bartender, :method => :delete, :data => { :confirm => "Are you sure?"},
                :title => "Delete #{@bartender.user.name}", :class => "btn btn-danger"%>

<% end %>

  <div>
    <%=  render "relationships/connect_button", :followed_id => @bartender.id, :type => RELATIONSHIP_TYPE_BARTENDER, :object => @bartender %>
  </div>

</div>

<% if @bartender.background %>
    <%= render "shared/full_screen_image", :image => @bartender.background_url %>
<% else %>
    <%= render "shared/full_screen_image", :image => "http://pad1.whstatic.com/images/thumb/3/30/Get-Traveling-Bartender-Gigs-Step-8.jpg/670px-Get-Traveling-Bartender-Gigs-Step-8.jpg"%>
<% end %>