config/routes.rb
SampleApp::Application.routes.draw do  

  resources :bartenders

  get '/pages/index' => redirect('/pages')
  
  resources :sessions, :only => [:new, :create, :destroy] do 
    collection do
      post :fb_signin
    end
  end
  
  resources :users do
  resources :bartenders, :only => [:create, :new]
    member do
      post :fb_unlink
      get :following, :followers       #makes users/1/following and following_user_path
    end
    collection do
      post :send_password_recovery
      get :password_recovery
      get :activate
      get :send_activation
      post :create_fb
      get :new_fb
    end
  end

  resources :base_objects
  resources :pages
  resources :relationships, :only => [:create, :destroy]

  root :to => "bartenders#index"
  get '/signup', :to => 'users#new'
  get '/contact', :to => 'pages#contact'
  get '/about', :to => 'pages#about'
  get '/signin', :to => 'sessions#new'
  get '/signout', :to => 'sessions#destroy'
  get '/admin', :to => 'pages#admin'
  get '/maintenance', :to => 'pages#maintenance'
  get '/error', :to => 'pages#error'
  get '/sitemap', :to => 'pages#site_map'
  get '/sitemap_xml', :to => 'pages#site_map_xml'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                 :integer         not null, primary key
#  name               :string(255)
#  email              :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  encrypted_password :string(255)
#  salt               :string(255)
#  admin              :boolean         default(FALSE)
#  fb_user_id         :integer
#

class User < ActiveRecord::Base      
  attr_accessor  :password, :fb_access_token  #defines new getter and setter
  attr_accessible :name, :email, :password, :password_confirmation, :fb_user_id, :fb_access_token

  #validation
  email_reg_ex = /\A[\w+\-.]+@[a-z\d.]+\.[a-z]+\z/i
  
  validates :name, :presence => true,
                    :length => { :maximum => 50 }
  validates :email, :presence => true,  
                    :format => { :with => email_reg_ex},
                    :uniqueness => { :case_sensitive => false}
  
  validates :password, :presence => true,
                       :confirmation => true,
                       :length => { :within => 6..40 }   

  #before we save this object, call the encrypt_password method on the object
  before_save :encrypt_password


  has_one :bartender

  #relationships
  has_many :relationships, :dependent => :destroy,
           :foreign_key => "follower_id" #since relationship table does not have user_id, must specify key to join to

  has_many :bartender_relationships, -> { where relationship_type: RELATIONSHIP_TYPE_BARTENDER }, :dependent => :destroy,
                           :foreign_key => "follower_id",
                           :class_name => "Relationship"

  has_many :following_bartenders,:through => :relationships, :source => :followed_bartenders

   ## or class << self
   ## def authenticate(       
  def User.authenticate(email, submitted_password)
     user = User.find_by_email(email); 
      
     (user && user.has_password?(submitted_password)) ? user : nil
       
  end                  
  
  def User.authenticate_with_salt(id, cookie_salt)
     user = find_by_id(id)
     (user && user.salt == cookie_salt) ? user : nil
  end
           
  def has_password?(submitted_password)
     encrypted_password == encrypt(submitted_password)
  end    


  def activate (key)
    if key == salt
      self.update_attribute( :activated, true)
    end
  end

  def image_url
    if self.fb_user_id
      "http://graph.facebook.com/#{self.fb_user_id}/picture?type=large"
    end
  end


  #relationship methods
  def follow(followed, type)
     Relationship.create(:follower_id => self.id, :followed_id => followed.id, :relationship_type => type)
  end

  def unfollow(followed, type)
    Relationship.where(:follower_id => self.id, :followed_id => followed.id, :relationship_type => type).delete_all
  end

  def follower_count
    if !followers
      0
    else
      followers.count
    end
  end

  def following? object
    if object.kind_of? User
       return self.following_users.include? object
    else
      return false
    end
  end

  def fb_connections
    User.where("fb_user_id in (?)",self.fb_friend_ids)
  end

  def fb_friend_ids

    begin
      graph = Koala::Facebook::API.new(self.fb_access_token)
      results = graph.get_connections('me', 'friends?fields=installed')
    rescue Exception  => e
      results = []
      puts "An error occurred, #{e}"
    end

    #for each id, insert to fb_friends, fb_id, id
    friends = []
    results.each do |result|
       friends << result["id"]
    end

    friends
  end

  private 
  
    def encrypt_password      
       self.salt = make_salt if new_record?
       if(self.password && !password.blank?)
        self.encrypted_password = encrypt(self.password)
       end
    end        
    
    def encrypt(string)
       secure_hash("#{salt}--#{string}")
    end  
                
    def make_salt
       secure_hash("#{Time.now.utc}--#{password}")
    end
    
    def secure_hash(string)
       Digest::SHA2.hexdigest(string)
    end         
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController   

  include ApplicationHelper
  require 'cgi'
  
  before_filter :authenticate, :except => [:password_recovery, :send_password_recovery,:send_activation, :activate,:show, :new, :create, :create_fb, :new_fb]
  before_filter :correct_user, :only => [:edit, :update]   
  before_filter :admin_user, :only => [:destroy]
  
  def new
    @tos_page = Page.find_by_title("user_terms")
    @title = "Sign up" 
    @user = User.new
  end  
  
  def show               
     id = params[:id]
     @user = User.find(id)  
     @title = @user.name
  end 
  
  def following
     @title = "Following"
     @user = User.find(params[:id])
     @users =  @user.following
     @users = @user.following.paginate(:page =>params[:page])
     render 'show_follow'
  end
  
  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(:page => params[:page])
    render 'show_follow'
  end
      
  def create 
    @user = User.new(params[:user])   
    if @user.save
      #redirect_to user_path(@user) OR
      #sign_in @user
      #redirect_to @user, :flash => {:success =>"Welcome to the sample app!"}
      session['activate_id'] = @user.id
      redirect_to '/users/send_activation'
    else
      @title = "Sign up"
      render 'new'
    end
  end
  def fb_unlink
    @user = User.find_by_id(current_user.id)
    @user.update_attribute(:fb_user_id, nil)
    @user.reload
    set_access_token nil
    current_user.reload
    redirect_to edit_user_path
  end
  
  def edit
     @title = "Edit user" 
     #note this assignment isnt needed since it is also called in the pre-filter         
     #@user = User.find(id = params[:id])
  end   
  
  def update          

    previous_email = @user.email
    if @user.update_attributes(params[:user])

      # if the user changes their email, we should revalidate it.
      if params[:user][:email] != previous_email
        @user.update_attribute("activated", false)
       send_activation_to @user
      end

       redirect_to(@user, :flash => {:success =>"Profile Updated."} )
    else 
       @title = "Edit user"  
       render 'edit'   
    end  
  end  
  
  def index
     @title = "All users" 
     
     #for will_paginate instead of
     #@users = User.all   
     @users = User.paginate(:page => params[:page])

  end      
  
  def destroy
     User.find(params[:id]).destroy  
     redirect_to users_path, :flash => {:success => "User Deleted"}
  end
  
  def new_fb
     @title = "Sign up" 
  end
  
  def create_fb
      encoded_sig, payload = params[:signed_request].split('.')
      if(encoded_sig && payload )
        sig = base64_url_decode(encoded_sig).unpack("H*")[0]
        data = JSON.parse base64_url_decode(payload)
          random_password = generated_password
          existing_user = User.find_by_email( data['registration']['email'])
          if(!existing_user)
            user = User.create!(:name => data['registration']['name'], :email => data['registration']['email'], 
                        :fb_user_id => data['user_id'], :password => random_password, 
                        :password_confirmation => random_password, :activated => true)
            user.update_attribute("activated",true)
            set_access_token data['oauth_token']
            sign_in(user)

            redirect_to user
          else
            if valid_facebook_cookie_or_signed_request? params[:signed_request]
              existing_user.update_attribute(:fb_user_id, @fb_id)
              set_access_token data['oauth_token'] #params[:access_token]
              sign_in(existing_user)

              redirect_to existing_user         
            end
        end
        return
      end    
      redirect_to root_path
  end


  def activate
    if(params[:key])
      dataUrl = params[:key]
      #data = CGI::unescape(dataUrl)
      #data64 = Base64.decode64 data
      data64 = base64_url_decode(dataUrl)
      data_decrypt = decrypt2 data64, CONSTANTS[  :activation_key]
      parsed_json = ActiveSupport::JSON.decode(data_decrypt)
      user_id = parsed_json['user_id']
      key = parsed_json['key']
      user = User.find(user_id)
      if user.activate key
        sign_in user
        redirect_to root_path
      end
    end
  end

  def send_activation
    user = User.find(session['activate_id'])
    send_activation_to user
  end

  def send_password_recovery
    user = User.find_by_email(params['email'])
    if(user)
      key = user.salt
      data = '{ "user_id" : "' + user.id.to_s + '", "key" : "' + key + '" }'
      key_encrypt = encrypt data, CONSTANTS[  :activation_key]
      key_64 = Base64.encode64 key_encrypt
      key64url =  CGI::escape(key_64)
      user.update_attribute(:recover_password, true)
      @url = "http://" + request.host_with_port + "/users/password_recovery?key=#{key64url}"
      UserMailer.password_recovery(user, @url)
      @email = user.email
      message = "Check your email to reset your password"
    else
      message = "Sorry, No user account was found with that email address."
    end

     redirect_to root_path, :flash => {:success =>message}
  end

  def password_recovery
    if(params[:key])
      dataUrl = params[:key]
      #data = CGI::unescape(dataUrl)
      #data64 = Base64.decode64 data
      data64 = base64_url_decode(dataUrl)
      data_decrypt = decrypt2 data64, CONSTANTS[  :activation_key]
      parsed_json = ActiveSupport::JSON.decode(data_decrypt)
      user_id = parsed_json['user_id']
      key = parsed_json['key']
      user = User.find(user_id)
      if key == user.salt && user.recover_password
        sign_in user
        redirect_to "/users/#{user.id}/edit", :flash => {:success =>"Please reset your password now."}
      else
        redirect_to root_path
      end

    end
  end

  
  private

  def send_activation_to user
    if(!user.activated)
      key = user.salt
      data = '{ "user_id" : "' + user.id.to_s + '", "key" : "' + key + '" }'
      key_encrypt = encrypt data, CONSTANTS[  :activation_key]
      key_64 = Base64.encode64 key_encrypt
      key64url =  CGI::escape(key_64)
      @url = "http://" + request.host_with_port + "/users/activate?key=#{key64url}"
      UserMailer.registration_activation( user, @url).deliver
      @email = user.email
    end
  end

  def correct_user     
     @user = User.find(params[:id]) 
     redirect_to(root_path) unless current_user?(@user) or current_user.admin
  end   
  
  def admin_user
       user = User.find(params[:id])
       redirect_to(root_path) if (!current_user.admin? || current_user?(user))
  end

end

app/helpers/users_helper.rb
module UsersHelper              
  
  def gravatar_for(user, options = { :size => 50 })
    #if(user.fb_user_id.nil?)
     gravatar_image_tag(user.email.downcase, :alt => user.name, 
                                             :class => "gravatar",
                                             :gravatar => options)
    #else
      
    #end
  end

  def image_for(user, options = { :size => 50 })
    if(user.image_url.nil?)
      gravatar_image_tag(user.email.downcase, :alt => user.name,
                         :class => "gravatar",
                         :gravatar => options)
    else
      image_tag user.image_url, :width => options[:size]
    end
  end

end

app/views/users/_fb_link.html.erb
<div id="fb-root"></div>    
<p>
  <%= link_to facebook_logo, "#", {:onclick => "Fb_Login();"} %>  Link
</p>

app/views/users/_fb_link_form.html.erb
	 <div id="follow_form">
		 <% if current_user.fb_user_id %>
			<%= render 'fb_unlink'%>
		 <% else%>
			<%= render 'fb_link'%>
		 <%end%>
	  </div>
	

app/views/users/_fb_unlink.html.erb
<%= form_tag fb_unlink_user_path, {:name=>'unlink_form'}  do %>
  <%= hidden_field_tag :fb_user_id, "" %>
<div id="fb-root"></div>    
    <p>
          <%= link_to facebook_logo, "#", {:onclick => "document.unlink_form.submit();"} %>  Unlink
    </p>
<% end %>

app/views/users/_fields.html.erb
<%= render 'shared/error_messages', :object => f.object %>   

<div class="form-group">
  <%= f.label :name%>
  <%= f.text_field :name, :class => "form-control"%>
</div>     

<div class="form-group">
  <%= f.label :email%>
  <%= f.text_field :email, :class => "form-control"%>
</div>

<div class="form-group">
  <%= f.label :password%>
  <%= f.password_field :password, :class => "form-control"%>
</div>

<div class="form-group">
  <%= f.label :password_confirmation, "Confirmation"%>
  <%= f.password_field :password_confirmation, :class => "form-control"%>
</div>

app/views/users/_user.html.erb
<li>
	<%= gravatar_for user, :size => 30 %>
	<%= link_to user.name, user %>	 
	
	<% if current_user.admin? %>
	| <%= link_to "delete", user, :method => :delete, :data => { :confirm => "Are you sure?"},
									:title => "Delete #{user.name}"%>
	<%end%>
	   
</li>

app/views/users/edit.html.erb
<div class="col-md-4">
<h1>Edit user</h1>

<%= form_for(@user) do |f| %>
                            
<!-- the argument :f below is to pass the f into the partial -->
<%= render 'fields', :f => f%>

<div class="actions">
  <%= f.submit "Update"%>
</div>

<% end %>
</div>
  <div class="col-md-4 well">
	 <%= gravatar_for @user%>     
	<!-- <a href = "http://gravatar.com/emails" target="_blank">change</a> -->

  <div id="link_form">
  	<%= render 'fb_link_form'%>
  </div>

</div>

<div class="col-md-5 well left">
  <h3>Bartender</h3>
  <% if @user.bartender %>
      <%= render "bartenders/bartender_thumb", :bartender => @user.bartender %>
  <% else %>
      <%= link_to "I tend bar", new_user_bartender_path(current_user), :class=> "btn btn-primary"%>
  <% end %>
</div>

app/views/users/index.html.erb
<h1>All users</h1>
      
<%= will_paginate%> <!-- note you can tell it the object to paginate as an argument if not by convention -->

<ul class="users"> 

	
	 <%= render @users %>   
	
	<!--  the above line works in place of this:
		<% @users.each do |user| %>  
	        <%=render 'user', :user => user %>
	      <%end%> 
		since rails will enumerate the array and render each with the class name -->
	
</ul> 

<%= will_paginate%>

app/views/users/new.html.erb
<div class="col-md-4">
  <h1>Sign up</h1>

<%= form_for(@user) do |f| %>

<%= render 'fields', :f => f %>  

    <i class="disclaimer">
      By pressing the button to sign up below, you are agreeing that you have read and agree to our  <%= link_to "Terms of Service", "#", :onclick => "$('#new_link_modal').modal('show')" %>
    </i>

<div class="actions">
  <%= f.submit "Sign up"%>
</div>
<% end %>
</div>

<%= render "shared/modal", :modal_id => "new_link_modal", :modal_title => "Terms of Service", :modal_content => ( render "pages/content", :page => @tos_page ) %>

app/views/users/new_fb.html.erb
<%=  render "shared/fb" %>
<h1>Sign up</h1>

<p>
	<div id="fb-root"></div>   
<div class="fb-registration" 
        data-fields="[{'name':'name'}, {'name':'email'}]" 
        data-redirect-uri="<%= root_url %>users/create_fb">
</div>	
</p>

app/views/users/send_activation.html.erb
<p>Thank you for registering. An email has been sent to you (<%= @email %>) to verify your email. Please check your inbox to activate your account.</p>

app/views/users/show.html.erb
		<div class="main left">
			 <h1> 
			   <%= gravatar_for @user %>
			   <%= @user.name %>

			</h1>    

		</div>
	    <div class="well right">
		    <strong>Name</strong> <%= @user.name%> <br/>
			<strong>URL</strong> <%= link_to user_path(@user.id), user_path(@user.id) %>  <br/>

	     </div>